version: 0.2

phases:
    install:
        commands:
            - yarn --prod
            - yarn add serverless-plugin-typescript
            - yarn add serverless-offline
    pre_build:
        commands:
            - yarn test
    build:
        commands:
            - echo 'no build set'
    post_build:
        commands:
            - echo 'deployment for the stage $(git branch -vv | grep \* | cut -d ' ' -f6 | grep -oP '^\[origin\/\K[^]]*')'
            - yarn deploy --stage=$(git branch -vv | grep \* | cut -d ' ' -f6 | grep -oP '^\[origin\/\K[^]]*')
