version: 0.2

phases:
    install:
        commands:
            - yarn --prod
            - yarn add serverless-plugin-typescript
            - yarn add serverless-offline
    pre_build:
        commands:
            - echo 'no pre-build set'
    build:
        commands:
            - echo 'no build set'
    post_build:
        commands:
            - yarn run deploy
