service: payline

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  envStage: ${env:BRANCH, 'master'}
  stage: ${opt:stage, self:custom.envStage}

provider:
  name: 'aws'
  runtime: 'nodejs6.10'
  stage: ${self:custom.stage} # Set the default stage used. Default is dev
  region: ${opt:region, 'eu-west-3'} # Overwrite the default region used. Default is us-east-1
  environment: ${file(./environment/${self:custom.stage}.yml)} # default env variables from the files per stage

functions:
  createWallet:
    handler: handler.createWallet
  getWallet:
    handler: handler.getWallet
  updateWallet:
    handler: handler.updateWallet
  disableWallet:
    handler: handler.disableWallet
  doWebPayment:
    handler: handler.doWebPayment
  doCapture:
    handler: handler.doCapture
  doRefund:
    handler: handler.doRefund
  scheduleWalletPayment:
    handler: handler.scheduleWalletPayment
  validateCard:
    handler: handler.validateCard
  doReset:
    handler: handler.doReset
  doAuthorization:
    handler: handler.doAuthorization
  doReAuthorization:
    handler: handler.doReAuthorization
  doWalletPayment:
    handler: handler.doWalletPayment
  transactionDetail:
    handler: handler.transactionDetail
  runAction:
    handler: handler.runAction
